---
- name: installing packages for python env
  become: true
  yum:
    name:
      - python3-pip
    update_cache: yes
- name: Creates directory
  file:
    path: ./basic-http-server
    state: directory

- name: Copy files to  remote webservers
  become: true
  copy:
    src:  website/drool
    #src:  website/traveler
    dest: /var/www/html
    
- name: Start httpd Service
  become: true
  service:
    name: httpd
    state: restarted