---
- name: installing packages for python env
  become: true
  yum:
    name:
      - python3-pip
    update_cache: yes
- name: Creates directory
  file:
    path: ./basic-http-server
    state: directory
- name: install apache2
  become: true
  yum:
    name:
      - httpd
    update_cache: yes
    state: latest
- name: Start httpd Service
  become: true
  service:
    name: httpd
    state: started